name: Maven Deploy

on: [push]

jobs:
  deploy:
    if: github.repository == 'Acerkoo/hello-ci'
     
    strategy:
      matrix:
        jdk_version: [11]
        mvn_action: [package]
        mysql_version: [5.7]
        os: [ubuntu-latest]
         
    services:
      mysql:
        image: mysql:${{ matrix.mysql_version }}
        env: 
          MYSQL_USER: username
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: szk
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK ${{ matrix.jdk_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk_version }}

      - name: Deploy to Github Package Registry
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_PASSWORD: ${{ secrets.GITHUB_PASSWORD }}
        run: |
          mvn --settings .github/settings.xml \
              --file pom.xml \
              -Dspring.config.location=docker/config/application.yml \
              deploy

      - name: publish docker
        uses: Acerkoo/Publish-Docker-Github-Action@2.7.1
        with:
          name: registry.cn-hangzhou.aliyuncs.com/imewalker/test:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.cn-hangzhou.aliyuncs.com
          dockerfile: Dockerfile
